# Generated by Django 5.2.10 on 2026-02-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyier', '0006_buyier_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyier',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='buyier',
            name='crop_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='buyier',
            name='farmer_name',
            field=models.CharField(max_length=100),
        ),
    ]
